services:
  bind:
    image: 100781/bind-dns
    container_name: bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/bind
      - ./bind-cache:/var/cache/bind
    restart: on-failure
