// Split-Horizon DNS
// Different answers based on source network

acl internal {
    192.168.0.0/16;
};

view "internal" {
    match-clients { internal; };
    recursion yes;

    zone "example.com" {
        type master;
        file "/bind/etc/zones/db.example.com.internal";
    };
};

view "external" {
    match-clients { any; };
    recursion no;

    zone "example.com" {
        type master;
        file "/bind/etc/zones/db.example.com.external";
    };
};
