// Authoritative Slave DNS Server
// Receives zone data from master only

options {
    directory "/var/cache/bind";

    listen-on { any; };
    listen-on-v6 { none; };

    recursion no;
    allow-query { any; };
};

zone "example.com" IN {
    type slave;
    masters { 192.168.100.11; };
    file "db.example.com";
};

zone "100.168.192.in-addr.arpa" IN {
    type slave;
    masters { 192.168.100.11; };
    file "db.192.168.100";
};
