// Authoritative Slave DNS Server
// Receives zone data from master only

/*
 * Deny transfers by default except for the listed hosts.
 * If we have other name servers, place them here.
 */
 acl trusted_transfer {
   192.168.122.10; // Primary DNS
   192.168.122.20; // Secondary DNS
 };
 
options {
    directory "/var/cache/bind";
    pid-file "/var/run/named/named.pid";
	
	listen-on { any; };                    # all ipv4 interfaces
    listen-on-v6 { none; };                # don't listen on ipv6

    recursion no;                          # no recursion
	
	notify no ;                            # noify on zone changes
	allow-transfer {  trusted_transfer; }; # IPs trusted for zone transfers
    
	allow-query { any; };                  # anyone who can access this server can query it
	allow-query-cache { any; };            # anyone who can access this server can query against the local cache
	
	dnssec-validation auto;                # default is yes since 9.5
	auth-nxdomain no;                      # conform to RFC1035
	empty-zones-enable yes;                # prevent certain ranges from becoming upstream noise

	allow-update { none; };                # dynamic updates for master zones are not accepted
};

zone "example.com" IN {
    type slave;
    masters { 192.168.100.10; };
    file "db.example.com";
	allow-transfer { trusted_transfer; };
};

zone "100.168.192.in-addr.arpa" IN {
    type slave;
    masters { 192.168.100.10; };
    file "db.192.168.100";
	allow-transfer { trusted_transfer; };
};
